name: Update Models JSON

on:
  push:
    branches:
      - main  # Triggers on every push to the main branch
    paths:
      - "public/models/*"  # Only triggers if files in the public/models directory change

jobs:
  update-models-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3 to use Node.js 16

      - name: Generate models.json
        run: |
          mkdir -p public/models  # Ensure the public/models directory exists
          files=$(ls public/models/*.glb)
          echo '[' > public/models/models.json
          for file in $files; do
            filename=$(basename "$file" .glb)
            echo "{\"name\": \"$filename\", \"file\": \"$file\"}," >> public/models/models.json
          done
          sed -i '$ s/,$//' public/models/models.json  # Remove trailing comma from the last entry
          echo ']' >> public/models/models.json

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/models/models.json
          git commit -m "Update models.json with latest model list"
          git push
